INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (1, 'https://img.tsn.ua/cached/082/tsn-f31867ea2500d8c162f8e1b3822736e1/thumbs/1116x628/b0/0d/7d58ebb0b74a90a9fc40a483bd1b0db0.jpeg', 'Молочні продукти');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (2, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTY-yl8ZgdJpLbX5EA3JP3Ae1PKm6-TPaSFnCVwmr3sMvRVPCTuYDFifM5E9rDMTP-8lkc&usqp=CAU', 'М''ясо та субпродукти');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (3, 'https://rivne1.tv/pics2/1607/i068101.jpg', 'Крупи');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (4, 'https://vomond.com.ua/wp-content/uploads/2020/07/1-1-1150x885.jpg', 'Риба');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (5, 'https://static2.gazeta.ua/img2/cache/gallery/805/805567_1_w_590.jpg?v=0', 'Морепродукти');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (6, 'https://images.1plus1.ua/uploads/articles/001/116/511/cd36324f4eaf3dea7e5629ab99bf0bd0_720x530.jpg?v=1665061152', 'Яйця та яєчні продукти');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (7, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR78n5wSbBjaE5ddxHz8B9kFE1Cb7ZCMhNZWIUhVuHYshzJLiWGnrQBAxMQLrtYcNk9Wt0&usqp=CAU', 'Снеки');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (8, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZzSMKN15fC8AbQOutDwSD_VY-QUwUQXO57Tcnz4blc3uKCTlgC8Zi2zsmXyWjz9Ukkjc&usqp=CAU', 'Кондитерські витвори');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (9, 'https://ukr.media/static/ba/aimg/3/7/9/379893_1.jpg', 'Овочі та овочеві продукти');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (10, 'https://www.greenmarket.com.ua/blog/wp-content/uploads/2014/07/zelen1-642x393.jpg', 'Зелень');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (11, 'https://yesfrukt.com/storage/source/f96cd9ce000c140442ae0b067aa84978/content/1/x5rKj4rEukLwUqOZCW_DG3RZ2NO14IZ7s.jpg.pagespeed.ic.1KAJ57PEk4.jpg', 'Фрукти');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (12, 'https://agropolit.com/media/news/600-400-m/00/06/6163/kzNQHFx8gbyhHfF-9709.jpg', 'Ягоди');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (13, 'https://harchi.info/files/8397-dried-fruits.jpg', 'Сухофрукти');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (14, 'https://phonoteka.org/uploads/posts/2021-05/1620235122_45-phonoteka_org-p-krasivii-fon-s-gribami-47.jpg', 'Гриби');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (15, 'https://foodbay.com/wiki/wp-content/uploads/2020/08/f856845d39-2.jpg', 'Масла');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (16, 'https://runday.org/wp-content/uploads/2017/11/nuts1.jpg', 'Горіхи');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (17, 'https://fruit-time.ua/images/blog/bq-6d6a4777-d252-4239-a733-2e56d4263de2.jpeg', 'Спеції');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (18, 'https://images.unian.net/photos/2022_03/thumb_files/1000_545_1647872294-5377.jpg?1', 'Мука та продукти з муки');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (19, 'https://euro-opt.shop/img/leoblog/b/lg-b-a2.jpg', 'Солодощі');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (20, 'https://obuchonok.com.ua/files/images/napoi.jpg', 'Напої');
INSERT INTO portaldb.product_category (PRODUCT_CATEGORY_ID, PHOTO_URL, TITLE) VALUES (21, 'https://tvoemisto.tv/media/gallery/full/a/l/alkogol_35607.jpg', 'Алкогольні напої');
